[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#686870"
blue = "#5CCFE6"
cyan = "#95E6CB"
green = "#A6CC70"
magenta = "#FFEE99"
red = "#F27983"
white = "#FFFFFF"
yellow = "#FFCC66"

[colors.normal]
black = "#191E2A"
blue = "#73D0FF"
cyan = "#95E6CB"
green = "#BAE67E"
magenta = "#FFD580"
red = "#FF3333"
white = "#C7C7C7"
yellow = "#FFA759"

[colors.primary]
background = "#202734"
foreground = "#CBCCC6"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 20000
multiplier = 3

[window]
decorations = "Buttonless"
dynamic_title = true
opacity = 0.9

[window.padding]
x = 8
y = 8

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "/opt/homebrew/bin/tmux a || /opt/homebrew/bin/tmux"]
